spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@planning-trips.piv1z.mongodb.net
      authentication-database: admin
      database: planning-trips
      auto-index-creation: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/PlanningTripsRealm

  main:
    allow-bean-definition-overriding: true
    #      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:9080/auth/realms/PlanningTripsRealm
#        registration:
#          keycloak:
#            client-id: login-app
#            client-secret: login-app
